name: user-admin-dashboard
services:
  web:
    build:
      context: ./
      target: final
    container_name: web
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
    ports:
      - '3000:3000'